// ---------------------------------------------------------------------------
//  T-Display-S3 — landscape dashboard
//
//  Four pages, cycled with the two on-board buttons, rendered on the 320x170
//  panel in landscape with smooth fonts generated by tools/make_vlw.py:
//
//    1. clock    NTP-synced time and date
//    2. weather  current conditions from Open-Meteo (no API key needed)
//    3. usage    Claude Code 5h / 7d limits, from tools/usage_server.py
//    4. system   WiFi, memory, battery, uptime
//
//  Over any of them, a banner the Mac can raise: POST a line to /notify on
//  tools/mac_stats_server.py and it goes up here, flashing the backlight, until
//  a button acknowledges it. Meant for the things worth interrupting for — a
//  Claude Code hook waiting on an answer, a build that failed.
//
//  The panel also picks its own page and brightness when left alone: it moves
//  to the CPU page while the Mac is loaded and to the usage page as a window
//  fills, and dims after sunset. It stays lit around the clock otherwise — this
//  is a panel on a desk, not a second screen for the Mac, and it is worth
//  reading while the Mac is locked, asleep, or shut in a clamshell.
//  Any button hands control back for two minutes. See "automatic behaviour".
//
//  Every page is composed into a full-screen sprite in PSRAM and pushed in one
//  go, so nothing flickers and partial redraws can't leave stale pixels behind.
//
//  The network comes from whichever link is answering: tools/usb_net_bridge.py
//  on the far end of the USB-C cable if it is running, otherwise WiFi. See
//  net_link.h — nothing on this side has to care which one it got.
//
//  Serial commands (115200, or any baud — the S3's USB CDC ignores it):
//    N   advance to the next page
//    S   dump the framebuffer, for tools/grab_screen.py
//    A   toggle automatic page selection
// ---------------------------------------------------------------------------

#include <Arduino.h>
#include <TFT_eSPI.h>
#include <WiFi.h>
#include <ArduinoJson.h>
#include <esp_system.h>
#include <esp_task_wdt.h>
#include <time.h>

#include "layout.h"
#include "net_link.h"
#include "secrets.h"
#include "../fonts/ui16.h"
#include "../fonts/ui24.h"
#include "../fonts/big64.h"

// --- board ------------------------------------------------------------------

#define PIN_POWER_ON 15   // gates the LCD rail — must be high before tft.init()
#define PIN_BTN_NEXT 14
#define PIN_BTN_ACT  0    // BOOT
#define PIN_BAT_ADC  4    // battery through a 1:2 divider

static const int16_t SCR_W = 320;   // landscape
static const int16_t SCR_H = 170;

// --- watchdog -----------------------------------------------------------------
//
// A panel meant to be read for weeks has to be able to come back from being
// wedged, because the failure mode otherwise is noticing days later that the
// clock stopped. The loop task is watched: the Arduino core feeds it once per
// pass through loop(), and serviceWhileBlocked() feeds it during a fetch that
// has not returned yet.
//
// Thirty seconds against a longest legitimate stall of about eight. Requests
// over the USB link are fed every couple of milliseconds by the idle hook, so
// they are not the constraint; a weather fetch over WiFi is. That one blocks
// inside HTTPClient, which offers no callback to feed from, for as long as its
// own timeout allows plus whatever DNS and the TLS handshake take.
//
// The margin is deliberate and the number is not a guess at the average. A
// watchdog that trips on a slow morning is a watchdog that gets switched off,
// and then it is not protecting anything. Recovering a hung panel in half a
// minute rather than fifteen seconds costs nothing worth having.
static const uint32_t WDT_TIMEOUT_S = 30;

static esp_reset_reason_t bootReason = ESP_RST_UNKNOWN;

static const char *resetName(esp_reset_reason_t r) {
  switch (r) {
    case ESP_RST_POWERON:   return "power";
    case ESP_RST_EXT:       return "reset";
    case ESP_RST_SW:        return "reflash";
    case ESP_RST_PANIC:     return "crash";
    case ESP_RST_INT_WDT:   return "int wdt";
    case ESP_RST_TASK_WDT:  return "wdt";
    case ESP_RST_WDT:       return "wdt";
    case ESP_RST_BROWNOUT:  return "brownout";
    case ESP_RST_DEEPSLEEP: return "sleep";
    default:                return "unknown";
  }
}

// Restarts the panel did not choose. Worth putting on the screen, because a
// watchdog that quietly recovers the panel at four in the morning is one you
// never learn anything from — the only other trace is an uptime that went back
// to zero while nobody was looking.
static bool bootWasAbnormal(esp_reset_reason_t r) {
  return r == ESP_RST_PANIC || r == ESP_RST_INT_WDT || r == ESP_RST_TASK_WDT ||
         r == ESP_RST_WDT   || r == ESP_RST_BROWNOUT;
}

static const int16_t BAR_TOP    = 20;          // status bar height
static const int16_t BAR_BOTTOM = 18;          // hint bar height
static const int16_t BODY_TOP   = BAR_TOP;
static const int16_t BODY_BOT   = SCR_H - BAR_BOTTOM;

// --- theme ------------------------------------------------------------------

static const uint16_t C_BG     = 0x0861;  // near-black
static const uint16_t C_BAR    = 0x18E3;
static const uint16_t C_TEXT   = 0xFFFF;
static const uint16_t C_DIM    = 0x8C71;
static const uint16_t C_ACCENT = 0x05FF;  // cyan
static const uint16_t C_WARM   = 0xFD20;  // orange
static const uint16_t C_OK     = 0x2FEB;  // green
static const uint16_t C_ERR    = 0xF9C7;  // red

// The two core clusters on the CPU page. Cyan and orchid rather than anything
// from the severity ramp above: those four colours all mean "how bad is this"
// somewhere else on the panel, and a P core at 90% is not a warning — it is a
// P core doing its job. Complementary hues so the two blocks separate at arm's
// length, which is the distance this page is actually read from.
static const uint16_t C_ECORE  = 0x05FF;  // cyan   — efficiency
static const uint16_t C_PCORE  = 0xF37F;  // orchid — performance

TFT_eSPI tft = TFT_eSPI();
TFT_eSprite fb = TFT_eSprite(&tft);

// --- font switching ---------------------------------------------------------
// TFT_eSPI routes drawString through the smooth font whenever one is loaded, so
// the built-in bitmap fonts are only reachable with no smooth font active.

static void useFont(const uint8_t *font) {
  fb.unloadFont();
  if (font) fb.loadFont(font);
}

// --- buttons ----------------------------------------------------------------

class Button {
public:
  explicit Button(uint8_t pin) : _pin(pin) {}

  void begin() { pinMode(_pin, INPUT_PULLUP); }

  // True once per press, after the level has been stable for the debounce window.
  bool pressed() {
    bool level = digitalRead(_pin) == LOW;
    uint32_t now = millis();

    if (level != _raw) { _raw = level; _changed = now; }
    if (now - _changed > 25 && level != _stable) {
      _stable = level;
      if (_stable) return true;
    }
    return false;
  }

private:
  uint8_t  _pin;
  bool     _raw = false, _stable = false;
  uint32_t _changed = 0;
};

Button btnNext(PIN_BTN_NEXT);
Button btnAct(PIN_BTN_ACT);

// --- weather ----------------------------------------------------------------

// Only what the combined page shows. Humidity, wind, and the daily high and low
// were dropped along with the separate weather page — none of them are
// requested either, so the response stays small.
struct Weather {
  bool     valid    = false;
  float    temp     = 0;
  float    feels    = 0;
  int      code     = -1;
  int      sunrise  = -1;   // minutes past local midnight, -1 if unknown
  int      sunset   = -1;
  uint32_t fetched  = 0;
  String   error;
};

Weather weather;

// WMO weather interpretation codes, grouped the way a forecast would read.
static const char *wmoText(int code) {
  switch (code) {
    case 0:  return "Clear sky";
    case 1:  return "Mainly clear";
    case 2:  return "Partly cloudy";
    case 3:  return "Overcast";
    case 45: case 48: return "Fog";
    case 51: case 53: case 55: return "Drizzle";
    case 56: case 57: return "Freezing drizzle";
    case 61: return "Slight rain";
    case 63: return "Moderate rain";
    case 65: return "Heavy rain";
    case 66: case 67: return "Freezing rain";
    case 71: case 73: case 75: return "Snow";
    case 77: return "Snow grains";
    case 80: return "Light showers";
    case 81: return "Showers";
    case 82: return "Violent showers";
    case 85: case 86: return "Snow showers";
    case 95: return "Thunderstorm";
    case 96: case 99: return "Thunderstorm, hail";
    default: return "Unknown";
  }
}

static uint16_t tempColor(float t) {
  if (t >= 35) return C_ERR;
  if (t >= 30) return C_WARM;
  if (t <= 20) return C_ACCENT;
  return C_OK;
}

// Minutes past midnight from an Open-Meteo local timestamp, "2026-08-09T18:45".
// -1 for anything that is not that shape, since a misparsed sunset would dim
// the panel at the wrong hour rather than fail visibly.
static int clockMinutes(const char *iso) {
  if (!iso || strlen(iso) < 16 || iso[10] != 'T' || iso[13] != ':') return -1;
  int h = atoi(iso + 11), m = atoi(iso + 14);
  if (h < 0 || h > 23 || m < 0 || m > 59) return -1;
  return h * 60 + m;
}

static bool fetchWeather() {
  if (!net::online()) {
    weather.error = "not connected";
    return false;
  }

  // The daily pair is not shown anywhere; it is what the backlight uses to
  // know it is night. Asking the forecast beats a hardcoded pair of hours,
  // which would only ever be right for one latitude.
  String url = String("https://api.open-meteo.com/v1/forecast?latitude=") +
               String(WEATHER_LAT, 4) + "&longitude=" + String(WEATHER_LON, 4) +
               "&current=temperature_2m,apparent_temperature,weather_code"
               "&daily=sunrise,sunset"
               "&timezone=" WEATHER_TZ_URL "&forecast_days=1";

  String payload;
  if (!net::get(url, payload, weather.error)) return false;

  JsonDocument doc;
  DeserializationError err = deserializeJson(doc, payload);

  if (err) {
    weather.error = String("JSON: ") + err.c_str();
    return false;
  }

  JsonObject cur = doc["current"];
  weather.temp  = cur["temperature_2m"]       | 0.0f;
  weather.feels = cur["apparent_temperature"] | 0.0f;
  weather.code  = cur["weather_code"]         | -1;

  weather.sunrise = clockMinutes(doc["daily"]["sunrise"][0] | "");
  weather.sunset  = clockMinutes(doc["daily"]["sunset"][0]  | "");

  weather.valid   = true;
  weather.fetched = millis();
  weather.error   = "";
  Serial.printf("[weather] %.1fC feels %.1fC code=%d sun %d..%d\n", weather.temp,
                weather.feels, weather.code, weather.sunrise, weather.sunset);
  return true;
}

// --- the services on the host ------------------------------------------------
//
// Three pages and the notification banner are fed by the two servers on the
// machine at the end of the cable. Where that machine is depends on how the
// request travels: over USB it is the bridge's own host, named by an alias the
// bridge resolves to loopback — the laptop moves between networks and its LAN
// address is not something to depend on. Over WiFi there is no bridge, so it
// has to be the address from secrets.h.
//
// Plain HTTP throughout: these serve a handful of numbers over a cable or the
// same subnet, so TLS would only cost handshake time and a second certificate
// path to keep working.
static String hostUrl(int port, const char *path) {
  String host = net::via() == net::Via::Usb ? String(USAGE_HOST_USB)
                                            : String(USAGE_HOST);
  return "http://" + host + ":" + String(port) + path;
}

// All four answer out of memory on the host, in single-digit milliseconds even
// with the machine loaded enough to be worth looking at. The default timeout is
// sized for a weather fetch the host has to do DNS and TLS for, and spending
// eight seconds of frozen panel to discover the bridge has stopped answering is
// the wrong trade. Two seconds rather than one because the host is sometimes
// the busy machine the CPU page exists to show.
static const uint32_t HOST_TIMEOUT = 2000;

// --- Claude Code usage limits -----------------------------------------------

struct Usage {
  bool     valid   = false;
  int      h5      = -1;      // percent of the 5-hour window used
  time_t   h5reset = 0;       // epoch the window rolls over, 0 if unknown
  int      d7      = -1;      // percent of the 7-day window used
  time_t   d7reset = 0;
  int      age     = -1;      // cache age in seconds, as reported at `fetched`
  uint32_t fetched = 0;
  String   error;
};

Usage usage;

// How stale the reading is *now*. `age` is only true as of the moment it was
// fetched, so the time since then has to be added — otherwise a failed poll
// leaves the age frozen at its last value and a dead link reads as fresh.
static int usageAgeNow() {
  if (!usage.valid || usage.age < 0) return -1;
  return usage.age + (int)((millis() - usage.fetched) / 1000);
}

static bool fetchUsage() {
  if (!net::online()) {
    usage.error = "not connected";
    return false;
  }

  String payload;
  if (!net::get(hostUrl(USAGE_PORT, "/usage"), payload, usage.error,
                HOST_TIMEOUT)) {
    return false;
  }

  JsonDocument doc;
  DeserializationError err = deserializeJson(doc, payload);
  if (err) {
    usage.error = String("JSON: ") + err.c_str();
    return false;
  }

  usage.h5      = doc["h5"]       | -1;
  usage.h5reset = doc["h5_reset"] | 0;
  usage.d7      = doc["d7"]       | -1;
  usage.d7reset = doc["d7_reset"] | 0;
  usage.age     = doc["age"]      | -1;

  usage.valid   = usage.h5 >= 0 || usage.d7 >= 0;
  usage.fetched = millis();
  usage.error   = usage.valid ? "" : "no reading yet";
  Serial.printf("[usage] 5h=%d%% 7d=%d%% age=%ds\n", usage.h5, usage.d7,
                usage.age);
  return usage.valid;
}

// --- Mac vitals -------------------------------------------------------------

struct MacStats {
  bool     valid    = false;
  int      batPct   = -1;
  String   batState;           // "discharging" / "charging" / "charged" / ...
  int      batMins  = -1;      // minutes left, -1 while the OS has no estimate
  float    load1    = -1;
  int      ncpu     = -1;
  int      memUsed  = -1;      // percent
  int      diskFree = -1;      // GB
  int      diskUsed = -1;      // percent
  String   screen;             // "on" / "locked" / "off"
  uint32_t up       = 0;       // seconds since the Mac booted
  int      age      = -1;      // snapshot age in seconds, as reported at `fetched`
  uint32_t fetched  = 0;
  String   error;
};

MacStats mac;

// How stale the reading is *now*, the same sum usageAgeNow() makes and for a
// sharper reason: the host samples these in a background thread, so a fetch
// that answered in a millisecond can still be carrying a snapshot from minutes
// ago if that thread has died. Without the server's own age the panel would
// call it fresh, because its fetch was.
static int macAgeNow() {
  if (!mac.valid) return -1;
  return (mac.age >= 0 ? mac.age : 0) + (int)((millis() - mac.fetched) / 1000);
}

static bool fetchMac() {
  if (!net::online()) {
    mac.error = "not connected";
    return false;
  }

  String payload;
  if (!net::get(hostUrl(MAC_PORT, "/mac"), payload, mac.error, HOST_TIMEOUT)) {
    return false;
  }

  JsonDocument doc;
  DeserializationError err = deserializeJson(doc, payload);
  if (err) {
    mac.error = String("JSON: ") + err.c_str();
    return false;
  }

  mac.batPct   = doc["bat_pct"]      | -1;
  mac.batState = doc["bat_state"]    | "";
  mac.batMins  = doc["bat_mins"]     | -1;
  mac.load1    = doc["load1"]        | -1.0f;
  mac.ncpu     = doc["ncpu"]         | -1;
  mac.memUsed  = doc["mem_used"]     | -1;
  mac.diskFree = doc["disk_free_gb"] | -1;
  mac.diskUsed = doc["disk_used"]    | -1;
  mac.screen   = doc["screen"]       | "";
  mac.up       = doc["uptime_s"]     | 0;
  mac.age      = doc["age"]          | -1;

  // The server answers with every field present but unknown ones set to -1, so
  // a reply that carries nothing readable is a failure, not an empty machine.
  mac.valid   = mac.batPct >= 0 || mac.load1 >= 0 || mac.memUsed >= 0;
  mac.fetched = millis();
  mac.error   = mac.valid ? "" : "no reading";
  Serial.printf("[mac] bat=%d%% %s load=%.2f mem=%d%% disk=%dGB screen=%s\n",
                mac.batPct, mac.batState.c_str(), mac.load1, mac.memUsed,
                mac.diskFree, mac.screen.c_str());
  return mac.valid;
}

// --- per-core CPU -----------------------------------------------------------

// An M3 Ultra reports 28 logical cores, so 16 was low enough to truncate a real
// machine. The page fits its columns to whatever arrives now, and the array is
// two bytes a core.
static const int MAX_CORES = 32;

struct CpuStats {
  bool     valid   = false;
  int      n       = 0;
  int      core[MAX_CORES] = {0};   // busy percent, efficiency cores first
  int      avg     = -1;
  int      ecores  = 0;
  int      pcores  = 0;
  uint32_t fetched = 0;
  String   error;
};

CpuStats cpu;

static bool fetchCpu() {
  if (!net::online()) {
    cpu.error = "not connected";
    return false;
  }

  String payload;
  if (!net::get(hostUrl(MAC_PORT, "/cpu"), payload, cpu.error, HOST_TIMEOUT)) {
    return false;
  }

  JsonDocument doc;
  DeserializationError err = deserializeJson(doc, payload);
  if (err) {
    cpu.error = String("JSON: ") + err.c_str();
    return false;
  }

  cpu.n = 0;
  for (JsonVariant v : doc["cores"].as<JsonArray>()) {
    if (cpu.n >= MAX_CORES) break;      // a machine wider than the panel
    cpu.core[cpu.n++] = v.as<int>();
  }

  cpu.avg     = doc["avg"]    | -1;
  cpu.ecores  = doc["ecores"] | 0;
  cpu.pcores  = doc["pcores"] | 0;
  cpu.valid   = cpu.n > 0;
  cpu.fetched = millis();
  cpu.error   = cpu.valid ? "" : "no cores reported";
  return cpu.valid;
}

// --- notifications ------------------------------------------------------------
//
// The one thing here that travels towards the panel rather than away from the
// Mac. tools/mac_stats_server.py holds a single message; anything on that
// machine can post one — a Claude Code hook that wants an answer, a build that
// failed — and it goes up over whatever page is showing until a button
// acknowledges it.
//
// The id is what makes a message new, and nothing else could: the same words
// posted twice are two events worth raising, and a message still standing an
// hour later is the one already dismissed.

struct Notify {
  uint32_t id      = 0;      // last id seen; 0 until the first poll answers
  String   msg;
  String   kind    = "info"; // "info" / "warn" / "alert"
  uint32_t ttl     = 0;      // seconds on screen, 0 = until dismissed
  bool     showing = false;
  uint32_t raised  = 0;      // millis the banner went up
  uint32_t flash   = 0;      // ms of backlight flashing loop() owes it
  bool     synced  = false;  // has a baseline id been adopted?
};

Notify notify;

// A message that arrived while the panel was off has usually already been dealt
// with by the person who saw it on the Mac, so the first poll adopts whatever
// is standing without raising it. Recent enough and it may still be waiting for
// someone — that one goes up.
static const int NOTIFY_STALE_ON_BOOT = 30;   // seconds

// How long a banner with no ttl of its own may hold the screen.
static const uint32_t NOTIFY_ALERT_MAX = 600;   // seconds

static bool fetchNotify() {
  if (!net::online()) return false;

  String payload, err;
  if (!net::get(hostUrl(MAC_PORT, "/notify"), payload, err, HOST_TIMEOUT)) {
    return false;
  }

  JsonDocument doc;
  if (deserializeJson(doc, payload)) return false;

  uint32_t id = doc["id"] | 0;
  if (id == notify.id) return false;      // the common case: nothing new
  notify.id = id;

  int age = doc["age"] | -1;
  bool first = !notify.synced;
  notify.synced = true;

  notify.msg  = doc["msg"].as<String>();
  notify.kind = doc["kind"] | "info";
  notify.ttl  = doc["ttl"] | 0;

  // An empty message is a retraction: the id moves so the panel notices, and
  // the banner comes down without anything replacing it.
  if (!notify.msg.length()) {
    notify.showing = false;
    return true;
  }

  if (first && !(age >= 0 && age <= NOTIFY_STALE_ON_BOOT)) return true;

  notify.showing = true;
  notify.raised  = millis();
  notify.flash   = notify.kind == "alert" ? 2500 : 1000;
  Serial.printf("[notify] #%lu %s: %s\n", (unsigned long)notify.id,
                notify.kind.c_str(), notify.msg.c_str());
  return true;
}

// --- battery ----------------------------------------------------------------

static float batteryVolts() {
  uint32_t mv = 0;
  for (int i = 0; i < 8; i++) mv += analogReadMilliVolts(PIN_BAT_ADC);
  return (mv / 8) * 2.0f / 1000.0f;   // undo the 1:2 divider
}

// --- automatic behaviour -----------------------------------------------------
//
// Two things the panel decides for itself: which page is worth showing, and how
// brightly to show it. Both for the same reason — a panel on a desk is read in
// glances, and the glance should land on whatever is currently true.
//
// Neither overrides a person. Any button hands control back for MANUAL_HOLD,
// and the automatic brightness gives way to the backlight toggle until the
// conditions that set it change.

enum Page : uint8_t { PAGE_NOW, PAGE_USAGE, PAGE_SYSTEM, PAGE_MAC, PAGE_CPU };
static const uint8_t PAGE_COUNT = 5;

static uint8_t page = PAGE_NOW;

static bool     autoPages   = true;   // 'A' over serial switches it off
static uint32_t manualUntil = 0;      // auto keeps out of the way until here
static int8_t   autoReturn  = -1;     // page to fall back to, -1 = none

static const uint32_t MANUAL_HOLD = 120000UL;   // two minutes

// A press means someone is driving. Auto stops choosing pages for a while, and
// forgets where it meant to return to — that plan was made for a panel nobody
// was watching.
static void handOverToUser() {
  manualUntil = millis() + MANUAL_HOLD;
  autoReturn = -1;
}

static bool userDriving() { return manualUntil && millis() < manualUntil; }

// Busy enough that the core bars are the page worth being on. Load is measured
// against the core count because that is the only way the number means the same
// thing on two machines; three quarters is where a Mac stops feeling idle
// without one compile tripping it.
static bool macBusy() {
  return mac.valid && mac.ncpu > 0 && mac.load1 >= mac.ncpu * 0.75f;
}

// A window close enough to its limit to change what you do next.
static bool usageTight() {
  return usage.valid && (usage.h5 >= 85 || usage.d7 >= 85);
}

static void autoGoTo(uint8_t want) {
  if (page == want) return;
  if (autoReturn < 0) autoReturn = page;
  page = want;
  Serial.printf("[auto] to page %u\n", page);
}

// Called once a pass; true when it moved.
//
// Each condition raises its page once and is then marked as shown, so a page
// re-chosen for as long as the condition holds is not a page you cannot leave.
// The mark is cleared by the condition passing, never by time: something still
// true when a banner comes down or a hold expires is still worth showing then,
// while a spike that came and went in the meantime has already cleared its own
// mark and stays quiet.
static bool autoPickPage() {
  static bool busyShown = false, tightShown = false;

  bool busy = macBusy(), tight = usageTight();
  if (!busy)  busyShown = false;
  if (!tight) tightShown = false;

  // Not while a banner is up: the page underneath is covered, and moving it
  // would only mean the dismissal lands somewhere unexpected.
  if (!autoPages || userDriving() || notify.showing) return false;

  uint8_t was = page;
  if (tight && !tightShown) {
    // Usage wins the tie: a full window stops the work, a busy machine only
    // slows it down.
    tightShown = true;
    autoGoTo(PAGE_USAGE);
  } else if (busy && !busyShown) {
    busyShown = true;
    autoGoTo(PAGE_CPU);
  } else if (!busy && !tight && autoReturn >= 0) {
    page = (uint8_t)autoReturn;
    autoReturn = -1;
    Serial.printf("[auto] back to page %u\n", page);
  }
  return page != was;
}

// --- backlight ---------------------------------------------------------------

static const uint8_t BL_DAY = 255, BL_NIGHT = 60;

static uint8_t backlight = BL_DAY;   // what the panel is lit at right now
static int16_t blManual  = -1;       // -1 = follow the rules below

// Sunset rather than a pair of hours: the hours would only ever be right for
// one latitude, and the forecast is already being fetched. No sun times means
// no dimming — guessing at the hour is worse than staying bright.
static bool isNight() {
  if (weather.sunrise < 0 || weather.sunset < 0) return false;
  time_t raw = time(nullptr);
  if (raw < 1700000000) return false;
  struct tm now;
  localtime_r(&raw, &now);
  int mins = now.tm_hour * 60 + now.tm_min;
  return mins < weather.sunrise || mins >= weather.sunset;
}

// Lit whenever it is powered. The Mac's own screen used to take this one dark
// with it, which is wrong for a panel whose whole job is being glanceable: the
// hours the Mac is locked, asleep or shut in a clamshell are exactly the hours
// nothing else on the desk is showing the time. Sunset is the only thing that
// moves the level, and it dims rather than blanks.
static uint8_t autoBacklight() {
  return isNight() ? BL_NIGHT : BL_DAY;
}

// A new notification flashes the panel as well as drawing the banner: the
// banner is only seen by someone already looking at it, and the flashing is
// what turns the head of someone who isn't.
static uint32_t flashUntil = 0, flashStep = 0;
static bool     flashDark  = false;

// The manual toggle holds until the automatic level would have changed anyway:
// turning the panel up to read something at night should not leave it blazing
// until morning.
static void applyBacklight() {
  static uint8_t lastAuto = BL_DAY;

  uint8_t want = autoBacklight();
  if (want != lastAuto) {
    lastAuto = want;
    blManual = -1;
  }

  uint8_t level = blManual >= 0 ? (uint8_t)blManual : want;
  if (level == backlight) return;

  backlight = level;
  // Held back mid-flash: the flash owns the pin until it finishes, and picks
  // the new level up when it hands it back.
  if (!flashUntil) analogWrite(TFT_BL, backlight);
  Serial.printf("[backlight] %u\n", backlight);
}

// Called every pass: runs the flash if one is owed, and otherwise keeps the
// panel at whatever the rules currently ask for. Driven from loop() rather than
// a delay() so a fetch or a redraw can land in the middle of a flash.
static void updateBacklight() {
  if (notify.flash) {
    flashUntil = millis() + notify.flash;
    flashStep  = 0;
    notify.flash = 0;
  }

  applyBacklight();

  if (!flashUntil) return;

  if (millis() > flashUntil || !notify.showing) {
    flashUntil = 0;
    flashDark = false;
    analogWrite(TFT_BL, backlight);
  } else if (millis() >= flashStep) {
    flashStep = millis() + 130;
    flashDark = !flashDark;
    analogWrite(TFT_BL, flashDark ? 8 : BL_DAY);
  }
}

// --- shared chrome ----------------------------------------------------------

// Label left, value right, within a column. Used by the weather and system pages.
// Values that would run into the label are clipped — a long SSID is otherwise
// wide enough to overlap it.
static void row(int16_t x, int16_t w, int16_t y, const char *label,
                const String &value, uint16_t color) {
  fb.setTextDatum(TL_DATUM);
  fb.setTextColor(C_DIM, C_BG);
  fb.drawString(label, x, y);

  int16_t avail = w - fb.textWidth(label) - 8;
  String shown = value;
  if (fb.textWidth(shown) > avail) {
    while (shown.length() > 1 && fb.textWidth(shown + "..") > avail) {
      shown.remove(shown.length() - 1);
    }
    shown += "..";
  }

  fb.setTextDatum(TR_DATUM);
  fb.setTextColor(color, C_BG);
  fb.drawString(shown, x + w, y);
}

static void drawStatusBar(const struct tm *now, bool timeValid) {
  fb.fillRect(0, 0, SCR_W, BAR_TOP, C_BAR);

  useFont(UiFont16);
  fb.setTextDatum(ML_DATUM);

  // The link name doubles as the connectivity indicator: "USB" when the host
  // bridge is answering, "WiFi" when the radio is carrying it instead.
  fb.setTextColor(net::online() ? C_OK : C_ERR, C_BAR);
  fb.drawString(net::viaName(), 6, BAR_TOP / 2);

  if (timeValid) {
    char stamp[16];
    strftime(stamp, sizeof(stamp), "%a %d %b", now);
    fb.setTextDatum(MR_DATUM);
    fb.setTextColor(C_TEXT, C_BAR);
    fb.drawString(stamp, SCR_W - 6, BAR_TOP / 2);
  }

  // Page dots, centred. The lit one doubles as the auto-page indicator: cyan
  // when the panel may pick the page itself, warm while a button press has it
  // holding off, white when automatic selection is switched off for good.
  uint16_t live = !autoPages ? C_TEXT : userDriving() ? C_WARM : C_ACCENT;
  for (uint8_t i = 0; i < PAGE_COUNT; i++) {
    int16_t x = SCR_W / 2 - (PAGE_COUNT - 1) * 6 + i * 12;
    fb.fillCircle(x, BAR_TOP / 2, 3, i == page ? live : C_DIM);
  }
}

static void drawHintBar(const char *left, const char *right) {
  fb.fillRect(0, BODY_BOT, SCR_W, BAR_BOTTOM, C_BAR);
  useFont(UiFont16);
  fb.setTextColor(C_DIM, C_BAR);
  fb.setTextDatum(ML_DATUM);
  fb.drawString(left, 6, BODY_BOT + BAR_BOTTOM / 2);
  fb.setTextDatum(MR_DATUM);
  fb.drawString(right, SCR_W - 6, BODY_BOT + BAR_BOTTOM / 2);
}

// --- the notification banner -------------------------------------------------

// The wrap itself lives in layout.h, shared with tests/layout_test.cpp. This is
// the seam: the measurement it cannot do for itself, in whatever font is loaded.
static int16_t measureText(const char *s) { return fb.textWidth(s); }

static uint16_t notifyColor() {
  if (notify.kind == "alert") return C_ERR;
  if (notify.kind == "warn")  return C_WARM;
  return C_ACCENT;
}

static const char *notifyHeading() {
  if (notify.kind == "alert") return "ALERT";
  if (notify.kind == "warn")  return "WARNING";
  return "NOTE";
}

static void drawBanner() {
  const int16_t x = 8, y = BODY_TOP + 6;
  const int16_t w = SCR_W - 16, h = BODY_BOT - y - 6;
  const uint16_t col = notifyColor();

  fb.fillRect(x, y, w, h, C_BAR);
  fb.drawRect(x, y, w, h, col);
  // A stripe down the edge, so how much this matters reads before the words do.
  fb.fillRect(x, y, 5, h, col);

  const int16_t tx = x + 16, tw = w - 24;

  useFont(UiFont16);
  fb.setTextDatum(TL_DATUM);
  fb.setTextColor(col, C_BAR);
  fb.drawString(notifyHeading(), tx, y + 7);

  // Anything left standing for a while was raised while nobody was looking;
  // saying so is the difference between "just now" and "since lunchtime".
  uint32_t age = (millis() - notify.raised) / 1000;
  if (age >= 10) {
    fb.setTextDatum(TR_DATUM);
    fb.setTextColor(C_DIM, C_BAR);
    fb.drawString(age < 90 ? String(age) + "s ago" : String(age / 60) + "m ago",
                  x + w - 8, y + 7);
  }

  // Big enough to read from across the room when the message is short, dropping
  // a size when it is long enough to need three lines instead of two. Decided
  // by wrapping and seeing, not by comparing the width against two lines' worth
  // of pixels: greedy wrapping leaves a ragged edge, so a string narrower than
  // that can still need the smaller font.
  String lines[3];
  bool cut = false;
  useFont(UiFont24);
  int n = wrapText(notify.msg, tw, 2, lines, measureText, &cut);
  if (cut) {
    useFont(UiFont16);
    n = wrapText(notify.msg, tw, 3, lines, measureText);
  }

  const int16_t top = y + 30, avail = h - 36;
  int16_t lh = fb.fontHeight() + 2;
  int16_t ty = top + (avail - n * lh) / 2;
  if (ty < top) ty = top;

  fb.setTextDatum(TL_DATUM);
  fb.setTextColor(C_TEXT, C_BAR);
  for (int i = 0; i < n; i++) fb.drawString(lines[i], tx, ty + i * lh);
}

// --- page 1: the time, the day, and how warm it is --------------------------
//
// The clock and the weather were separate pages. Merged, they keep only what is
// worth a glance — time, date, temperature, and the two lines of forecast that
// change what you wear. Place, apparent temperature, humidity and wind went
// with the page they were on, and are no longer fetched.
//
// The geometry here is measured, not guessed: at the big face "09:44" is 165px
// and a temperature carrying its tenth is 149px, which together overflow the
// 304px between the margins. Rounding the temperature to the degree is what
// makes the two fit on one line — and it is the figure you actually read from
// across a room.

static void pageNow(const struct tm *now, bool timeValid) {
  // Drawn first because it is right-aligned: the seconds beside the clock need
  // to know where the temperature starts before they can claim their space.
  int16_t tempLeft = SCR_W;
  if (weather.valid) {
    String t = String((int)lroundf(weather.temp)) + "°";
    useFont(BigFont64);
    fb.setTextDatum(MR_DATUM);
    fb.setTextColor(tempColor(weather.temp), C_BG);
    fb.drawString(t, SCR_W - 8, 60);
    tempLeft = SCR_W - 8 - fb.textWidth(t);
  }

  char hhmm[6] = "--:--";
  if (timeValid) strftime(hhmm, sizeof(hhmm), "%H:%M", now);

  useFont(BigFont64);
  fb.setTextDatum(ML_DATUM);
  fb.setTextColor(timeValid ? C_TEXT : C_DIM, C_BG);
  fb.drawString(hhmm, 8, 60);
  int16_t timeEnd = 8 + fb.textWidth(hhmm);

  // Seconds are the one thing here that is not essential; they earn their place
  // by showing the panel is alive, and give it up when the temperature is wide
  // enough to need the room.
  if (timeValid) {
    char ss[4];
    strftime(ss, sizeof(ss), "%S", now);
    useFont(UiFont16);
    if (timeEnd + 8 + fb.textWidth(ss) < tempLeft - 8) {
      fb.setTextDatum(ML_DATUM);
      fb.setTextColor(C_ACCENT, C_BG);
      fb.drawString(ss, timeEnd + 8, 74);
    }
  }

  // Middle line: what it feels like on the left, the conditions on the right.
  useFont(UiFont16);
  if (weather.valid) {
    // The label stays dim and the figure carries the colour: when the air is
    // 31° and it feels like 38°, that gap is the whole point of the line.
    const char *label = "Feels like";
    fb.setTextDatum(ML_DATUM);
    fb.setTextColor(C_DIM, C_BG);
    fb.drawString(label, 8, 106);

    fb.setTextColor(tempColor(weather.feels), C_BG);
    fb.drawString(String((int)lroundf(weather.feels)) + "°",
                  8 + fb.textWidth(label) + 6, 106);

    fb.setTextDatum(MR_DATUM);
    fb.setTextColor(C_DIM, C_BG);
    fb.drawString(wmoText(weather.code), SCR_W - 8, 106);
  } else {
    fb.setTextDatum(MR_DATUM);
    fb.setTextColor(C_ERR, C_BG);
    fb.drawString(weather.error.length() ? weather.error : String("loading..."),
                  SCR_W - 8, 106);
  }

  // Bottom line: the date on the left, spelled out — the status bar only has
  // room to abbreviate it, and never carries the year.
  char date[48];
  if (timeValid) {
    char wd[16], mon[16];
    strftime(wd, sizeof(wd), "%A", now);
    strftime(mon, sizeof(mon), "%B", now);
    // Built by hand rather than with %d, which pads single-digit days with a zero.
    snprintf(date, sizeof(date), "%s %d %s %d", wd, now->tm_mday, mon,
             now->tm_year + 1900);
  } else {
    snprintf(date, sizeof(date), "%s",
             net::online() ? "syncing the clock..." : "no network link");
  }
  fb.setTextDatum(ML_DATUM);
  fb.setTextColor(C_DIM, C_BG);
  fb.drawString(date, 8, 130);

  // Opposite it, the place the reading is for — giving way to the reading's age
  // once that stops being fresh. The place is fixed configuration you already
  // know; a forecast refreshed every ten minutes going half an hour without one
  // is the part worth the space. Drawn only if the date leaves room, since the
  // longest weekday and month together run most of the way across.
  String corner = WEATHER_PLACE;
  uint16_t cornerCol = C_DIM;
  if (weather.valid) {
    uint32_t stale = (millis() - weather.fetched) / 60000;
    if (stale >= 30) {
      corner = String(stale) + "m ago";
      cornerCol = C_WARM;
    }
  }
  if (8 + fb.textWidth(date) + 10 < SCR_W - 8 - fb.textWidth(corner)) {
    fb.setTextDatum(MR_DATUM);
    fb.setTextColor(cornerCol, C_BG);
    fb.drawString(corner, SCR_W - 8, 130);
  }
}

// --- page 2: Claude Code usage ----------------------------------------------

// Cool-to-hot ramp across a filled bar, matching the status line in the
// terminal: green while there is room, red as the window fills.
static uint16_t rampColor(float t) {
  uint8_t r, g;
  if (t < 0.5f) { r = (uint8_t)(t * 2 * 255); g = 255; }
  else          { r = 255; g = (uint8_t)((1 - t) * 2 * 255); }
  return ((r & 0xF8) << 8) | ((g & 0xFC) << 3);
}

static uint16_t severityColor(int pct) {
  if (pct >= 85) return C_ERR;
  if (pct >= 60) return C_WARM;
  return C_OK;
}

// "2d 5h" / "3h 05m" / "12m" — a span at the precision that still matters at
// its size. Empty for anything non-positive, so callers can test the result
// rather than the input.
static String spanText(long seconds) {
  if (seconds <= 0) return "";
  long dd = seconds / 86400, hh = (seconds % 86400) / 3600,
       mm = (seconds % 3600) / 60;
  char buf[16];
  if (dd > 0)      snprintf(buf, sizeof(buf), "%ldd %ldh", dd, hh);
  else if (hh > 0) snprintf(buf, sizeof(buf), "%ldh %02ldm", hh, mm);
  else             snprintf(buf, sizeof(buf), "%ldm", mm);
  return String(buf);
}

// The number decisions actually get made on: how long until the window rolls.
static String countdown(time_t reset, time_t now) {
  return spanText((long)(reset - now));
}

// Wall-clock reset, with the weekday once it is more than a day out.
static String resetClock(time_t reset, time_t now) {
  if (reset <= 0) return "";
  struct tm t;
  localtime_r(&reset, &t);
  char buf[16];
  strftime(buf, sizeof(buf), reset < now + 86400 ? "%H:%M" : "%a %H:%M", &t);
  return String(buf);
}

static void gauge(const char *label, int16_t y, int pct, time_t reset,
                  time_t now, bool timeValid) {
  const int16_t BX = 44, BW = 196, BH = 14;

  useFont(UiFont16);
  fb.setTextDatum(ML_DATUM);
  fb.setTextColor(C_DIM, C_BG);
  fb.drawString(label, 8, y + BH / 2);

  if (pct < 0) {
    fb.fillRect(BX, y, BW, BH, C_BAR);
    fb.setTextDatum(ML_DATUM);
    fb.drawString("waiting for a reading", BX + 8, y + BH / 2);
    return;
  }

  // Filled portion drawn column by column so the ramp is a gradient rather
  // than a handful of discrete blocks.
  int16_t filled = (int16_t)((long)BW * pct / 100);
  if (filled > BW) filled = BW;
  if (filled < 2 && pct > 0) filled = 2;
  fb.fillRect(BX, y, BW, BH, C_BAR);
  for (int16_t x = 0; x < filled; x++) {
    fb.drawFastVLine(BX + x, y, BH, rampColor((float)x / BW));
  }

  useFont(UiFont24);
  fb.setTextDatum(MR_DATUM);
  fb.setTextColor(severityColor(pct), C_BG);
  fb.drawString(String(pct) + "%", SCR_W - 8, y + BH / 2);

  // Detail line: when the window rolls over, and how long that is away.
  if (!timeValid || reset <= 0) return;

  useFont(UiFont16);
  fb.setTextDatum(ML_DATUM);
  fb.setTextColor(C_DIM, C_BG);

  String when = "resets " + resetClock(reset, now);
  int16_t ty = y + BH + 12;
  fb.drawString(when, BX, ty);

  // The separator is drawn rather than typed: make_vlw.py only bakes printable
  // ASCII plus the degree sign, so a middle dot would render as a blank box.
  String left = countdown(reset, now);
  if (left.length()) {
    int16_t x = BX + fb.textWidth(when) + 9;
    fb.fillCircle(x, ty, 1, C_DIM);
    fb.drawString("in " + left, x + 9, ty);
  }
}

static void pageUsage(time_t now, bool timeValid) {
  useFont(UiFont16);
  fb.setTextDatum(ML_DATUM);
  fb.setTextColor(C_ACCENT, C_BG);
  fb.drawString("Claude Code usage", 8, BODY_TOP + 10);

  if (!usage.valid) {
    useFont(UiFont16);
    fb.setTextDatum(MC_DATUM);
    fb.setTextColor(C_ERR, C_BG);
    fb.drawString(usage.error.length() ? usage.error : String("loading..."),
                  SCR_W / 2, 90);
    return;
  }

  // How old the reading is matters as much as the reading: the cache only moves
  // when Claude Code renders its status line, so a quiet hour leaves it stale.
  int age = usageAgeNow();
  if (age >= 0) {
    String label = age < 90 ? String(age) + "s ago" : String(age / 60) + "m ago";
    fb.setTextDatum(MR_DATUM);
    fb.setTextColor(age > 900 ? C_WARM : C_DIM, C_BG);
    fb.drawString(label, SCR_W - 8, BODY_TOP + 10);
  }

  gauge("5H", 46, usage.h5, usage.h5reset, now, timeValid);
  gauge("7D", 98, usage.d7, usage.d7reset, now, timeValid);
}

// --- page 3: system ---------------------------------------------------------

static void pageSystem() {
  net::Via link = net::via();
  bool wifi = link == net::Via::Wifi;
  const int16_t LX = 8, RX = 172, CW = 140;

  useFont(UiFont16);
  int16_t y = BODY_TOP + 8;

  // What is carrying the data, not what the radio happens to be doing: the USB
  // bridge wins even when WiFi is also associated.
  String where = link == net::Via::Usb ? String("USB host")
                 : wifi                ? WiFi.SSID()
                                       : String("--");
  row(LX, CW, y, "Link", where, link == net::Via::None ? C_ERR : C_OK);
  row(RX, CW, y, "Heap", String(ESP.getFreeHeap() / 1024) + " KB", C_TEXT);
  y += 24;

  // RSSI only means something on the radio; over USB the field would otherwise
  // show a stale number from whenever WiFi last associated.
  row(LX, CW, y, "Signal", wifi ? String(WiFi.RSSI()) + " dBm" : String("--"),
      C_TEXT);
  // MB, not KB — "Free PSRAM" next to "8083 KB" collided in a 140px column.
  row(RX, CW, y, "PSRAM", String(ESP.getFreePsram() / 1048576.0f, 1) + " MB",
      C_TEXT);
  y += 24;

  row(LX, CW, y, "IP", wifi ? WiFi.localIP().toString() : String("--"), C_TEXT);
  row(RX, CW, y, "Battery", String(batteryVolts(), 2) + " V", C_TEXT);
  y += 24;

  uint32_t s = millis() / 1000;
  char up[16];
  snprintf(up, sizeof(up), "%luh %02lum", (unsigned long)(s / 3600),
           (unsigned long)((s / 60) % 60));
  row(LX, CW, y, "Uptime", up, C_TEXT);

  // The clock speed gives way to why the panel last restarted, the same trade
  // the weather page makes when it drops the place name for the reading's age:
  // a figure that is always 240 MHz is worth less than the one fact that
  // explains why the uptime beside it just went back to zero. It only appears
  // when there is something to say, so the usual state of this page is the
  // usual reading.
  if (bootWasAbnormal(bootReason)) {
    row(RX, CW, y, "Boot", resetName(bootReason), C_WARM);
  } else {
    row(RX, CW, y, "CPU", String(getCpuFrequencyMhz()) + " MHz", C_TEXT);
  }

  fb.drawFastVLine(SCR_W / 2, BODY_TOP + 6, BODY_BOT - BODY_TOP - 12, C_BAR);
}

// --- page 4: the Mac at the other end of the cable ---------------------------

// Charge reads the opposite way to the usage windows: a full bar is the good
// end, so severityColor() would paint a healthy battery red.
static uint16_t chargeColor(int pct) {
  if (pct <= 20) return C_ERR;
  if (pct <= 50) return C_WARM;
  return C_OK;
}

static void pageMac() {
  useFont(UiFont16);
  fb.setTextDatum(ML_DATUM);
  fb.setTextColor(C_ACCENT, C_BG);
  fb.drawString("MacBook", 8, BODY_TOP + 10);

  if (!mac.valid) {
    fb.setTextDatum(MC_DATUM);
    fb.setTextColor(C_ERR, C_BG);
    fb.drawString(mac.error.length() ? mac.error : String("loading..."),
                  SCR_W / 2, 90);
    return;
  }

  // A failed poll leaves the last reading on screen rather than blanking the
  // page, so the age has to be visible or a charge figure from hours ago reads
  // as current. Shown only once it is old enough to mislead — labelling a
  // fresh number "0s ago" every second is noise.
  int age = macAgeNow();
  if (age > 90) {
    fb.setTextDatum(ML_DATUM);
    fb.setTextColor(C_WARM, C_BG);
    fb.drawString(String(age / 60) + "m ago",
                  8 + fb.textWidth("MacBook") + 10, BODY_TOP + 10);
  }

  // Power state sits opposite the heading — the one word that changes what the
  // battery number means.
  if (mac.batState.length()) {
    bool onPower = mac.batState != "discharging";
    fb.setTextDatum(MR_DATUM);
    fb.setTextColor(onPower ? C_OK : C_DIM, C_BG);
    fb.drawString(mac.batState, SCR_W - 8, BODY_TOP + 10);
  }

  // Charge bar, sharing the usage gauge's geometry so the two pages line up.
  const int16_t BX = 44, BW = 196, BH = 14, BY = 48;
  fb.setTextDatum(ML_DATUM);
  fb.setTextColor(C_DIM, C_BG);
  fb.drawString("BAT", 8, BY + BH / 2);

  fb.fillRect(BX, BY, BW, BH, C_BAR);
  if (mac.batPct >= 0) {
    int16_t filled = (int16_t)((long)BW * mac.batPct / 100);
    if (filled > BW) filled = BW;
    if (filled < 2 && mac.batPct > 0) filled = 2;
    // Filled flat rather than with the usage page's ramp: there the gradient
    // tracks a cost rising toward its limit, here it would just be decoration.
    fb.fillRect(BX, BY, filled, BH, chargeColor(mac.batPct));

    useFont(UiFont24);
    fb.setTextDatum(MR_DATUM);
    fb.setTextColor(chargeColor(mac.batPct), C_BG);
    fb.drawString(String(mac.batPct) + "%", SCR_W - 8, BY + BH / 2);
  }

  // Detail line under the bar, same shape as the usage gauge's: the separator
  // is a drawn dot because make_vlw.py bakes no middle dot to type.
  useFont(UiFont16);
  fb.setTextDatum(ML_DATUM);
  fb.setTextColor(C_DIM, C_BG);

  String left = spanText((long)mac.batMins * 60);
  String head = left.length() ? left + " left" : String("no estimate");
  int16_t ty = BY + BH + 16;
  fb.drawString(head, BX, ty);

  String upFor = spanText((long)mac.up);
  if (upFor.length()) {
    int16_t x = BX + fb.textWidth(head) + 9;
    fb.fillCircle(x, ty, 1, C_DIM);
    fb.drawString("up " + upFor, x + 9, ty);
  }

  // Resource grid, laid out like the system page so the two read as siblings.
  const int16_t LX = 8, RX = 172, CW = 140;
  int16_t y = 100;

  String load = mac.load1 >= 0 ? String(mac.load1, 2) : String("--");
  if (mac.load1 >= 0 && mac.ncpu > 0) load += "/" + String(mac.ncpu);
  // Load is per-core-count, so the same number is fine on one Mac and pinned on
  // another; colour it against this machine's cores rather than a fixed bar.
  uint16_t loadCol = C_TEXT;
  if (mac.load1 >= 0 && mac.ncpu > 0) {
    if (mac.load1 >= mac.ncpu)          loadCol = C_ERR;
    else if (mac.load1 >= mac.ncpu / 2) loadCol = C_WARM;
  }
  row(LX, CW, y, "Load", load, loadCol);
  row(RX, CW, y, "Memory",
      mac.memUsed >= 0 ? String(mac.memUsed) + "%" : String("--"),
      mac.memUsed >= 0 ? severityColor(mac.memUsed) : C_DIM);
  y += 24;

  row(LX, CW, y, "Disk free",
      mac.diskFree >= 0 ? String(mac.diskFree) + " GB" : String("--"), C_TEXT);
  row(RX, CW, y, "Disk used",
      mac.diskUsed >= 0 ? String(mac.diskUsed) + "%" : String("--"),
      mac.diskUsed >= 0 ? severityColor(mac.diskUsed) : C_DIM);

  fb.drawFastVLine(SCR_W / 2, 94, BODY_BOT - 100, C_BAR);
}

// --- page 5: every core, once a second ---------------------------------------

static void pageCpu() {
  useFont(UiFont16);
  fb.setTextDatum(ML_DATUM);
  fb.setTextColor(C_ACCENT, C_BG);
  fb.drawString("CPU", 8, BODY_TOP + 10);

  if (!cpu.valid) {
    fb.setTextDatum(MC_DATUM);
    fb.setTextColor(C_ERR, C_BG);
    fb.drawString(cpu.error.length() ? cpu.error : String("loading..."),
                  SCR_W / 2, 90);
    return;
  }

  // Only colour the clusters apart when the Mac actually said where the line
  // falls. Without it every core would come out looking like a P core, which is
  // a worse answer than the one flat colour this page used to have.
  const bool split = cpu.ecores > 0 && cpu.pcores > 0;

  // Core mix beside the heading, each half in its own colour. That makes it the
  // key for the bars below as well as the count — the alternative was a legend
  // taking up room on a page that is already a row of columns wide.
  if (split) {
    const int16_t ly = BODY_TOP + 10;
    int16_t lx = 8 + fb.textWidth("CPU") + 10;
    String e = String(cpu.ecores) + "E";

    fb.setTextColor(C_ECORE, C_BG);
    fb.drawString(e, lx, ly);
    lx += fb.textWidth(e);

    fb.setTextColor(C_DIM, C_BG);
    fb.drawString("+", lx, ly);
    lx += fb.textWidth("+");

    fb.setTextColor(C_PCORE, C_BG);
    fb.drawString(String(cpu.pcores) + "P", lx, ly);
  }

  if (cpu.avg >= 0) {
    useFont(UiFont24);
    fb.setTextDatum(MR_DATUM);
    fb.setTextColor(severityColor(cpu.avg), C_BG);
    fb.drawString(String(cpu.avg) + "%", SCR_W - 8, BODY_TOP + 10);
  }

  // One column per core, plus one wider gap where the clusters meet. The
  // sizing is in layout.h, shared with the test that checks every core count
  // from one to MAX_CORES still lands on the panel.
  const int16_t MARGIN = 4;
  const int16_t SPLIT  = split ? 10 : 0;
  const int16_t TOP = 48, BOT = 142, H = BOT - TOP;

  const CpuBars bars = cpuBarLayout(cpu.n, SCR_W, MARGIN, SPLIT);
  const int16_t bw = bars.bw, gap = bars.gap;

  // The unlit part of each column carries the cluster colour too, at a level
  // that stays behind the fill. Without it an idle Mac is a row of identical
  // grey columns and the whole distinction disappears exactly when the gap
  // between the groups is the only thing left to read.
  const uint16_t TRACK_E = 0x0166, TRACK_P = 0x3046;

  int16_t span = cpu.n * bw + (cpu.n - 1) * gap + SPLIT;
  int16_t x0 = (SCR_W - span) / 2;
  if (x0 < MARGIN) x0 = MARGIN;

  for (int i = 0; i < cpu.n; i++) {
    bool perf = split && i >= cpu.ecores;

    int16_t x = x0 + i * (bw + gap) + (perf ? SPLIT : 0);
    // Nothing should reach this now that the width is fitted; it stays as the
    // guard against a core count the arithmetic above cannot squeeze in.
    if (x + bw > SCR_W - MARGIN) break;

    int pct = cpu.core[i];
    if (pct < 0) pct = 0;
    if (pct > 100) pct = 100;

    uint16_t hue   = !split ? C_ACCENT : (perf ? C_PCORE : C_ECORE);
    uint16_t track = !split ? C_BAR    : (perf ? TRACK_P : TRACK_E);

    fb.fillRect(x, TOP, bw, H, track);

    int16_t filled = (int16_t)((long)H * pct / 100);
    if (filled < 2 && pct > 0) filled = 2;
    // Grown from the bottom, so a row of columns reads as level rather than as
    // a set of separate bars that happen to share a baseline.
    if (filled > 0) {
      fb.fillRect(x, BOT - filled, bw, filled, hue);
    }
  }
}

// --- render -----------------------------------------------------------------

// At file scope because the idle hook below redraws too. Both it and loop()
// clear it to force a redraw on the next pass rather than waiting out the
// second.
static uint32_t lastDraw = 0;

static void render() {
  time_t raw = time(nullptr);
  struct tm now;
  localtime_r(&raw, &now);
  bool timeValid = raw > 1700000000;   // anything earlier means NTP hasn't landed

  fb.fillSprite(C_BG);

  switch (page) {
    case PAGE_NOW:    pageNow(&now, timeValid);  break;
    case PAGE_USAGE:  pageUsage(raw, timeValid); break;
    case PAGE_SYSTEM: pageSystem();              break;
    case PAGE_MAC:    pageMac();                 break;
    case PAGE_CPU:    pageCpu();                 break;
  }

  drawStatusBar(&now, timeValid);

  if (notify.showing) {
    // Over the page rather than instead of it: the status bar keeps saying
    // which page is underneath, so dismissing lands somewhere expected.
    drawBanner();
    drawHintBar("any button  dismiss", "");
  } else {
    // BOOT refetches on the pages whose data is polled slowly enough to be
    // worth hurrying, and is the backlight toggle everywhere else — including
    // the CPU page, which already refreshes every second on its own.
    bool fetches = page == PAGE_NOW || page == PAGE_USAGE || page == PAGE_MAC;
    drawHintBar("IO14  next page", fetches ? "BOOT  refresh" : "BOOT  backlight");
  }

  fb.pushSprite(0, 0);
}

// Raw RGB565 dump of the sprite, so the host can see exactly what the panel
// shows. Reassembled by tools/grab_screen.py.
static void dumpScreen() {
  Serial.printf("\nSCREEN %d %d\n", SCR_W, SCR_H);
  Serial.flush();
  Serial.write((const uint8_t *)fb.getPointer(), (size_t)SCR_W * SCR_H * 2);
  Serial.flush();
}

// --- staying alive through a fetch -------------------------------------------
//
// A fetch blocks loop() until the host answers or the timeout runs out, and
// nothing else runs in that window: the clock stops, a press goes unseen, and a
// banner that arrived a moment ago sits undrawn. For the host's own services
// that window is now milliseconds, but the weather still goes out to the
// internet on the host's behalf and is allowed its eight seconds — and eight
// seconds of a stopped clock is precisely how a working panel comes to look
// like a crashed one.
//
// net_link calls this while it waits. It does the two things that must not
// stop, and deliberately not the third: serial commands are left alone, because
// draining them here would take bytes from the reader that is mid-request, and
// a framebuffer dump would land in the middle of the response it is waiting on.

static bool pendingNext = false, pendingAct = false;

static void serviceWhileBlocked() {
  // Latched rather than acted on. pressed() reports an edge exactly once, so
  // consuming it here and doing nothing with it would turn a press during a
  // fetch into a press that never happened — and the fetch is the very moment
  // someone jabs the button, because the panel looks stuck.
  if (btnNext.pressed()) pendingNext = true;
  if (btnAct.pressed())  pendingAct  = true;

  // The core feeds the watchdog once per pass through loop(), and loop() has
  // not returned: without this a fetch that takes longer than WDT_TIMEOUT_S
  // would be indistinguishable from a hang and get the panel restarted for
  // doing its job.
  feedLoopWDT();

  updateBacklight();

  if (millis() - lastDraw >= 1000) {
    lastDraw = millis();
    render();
  }
}

// --- setup / loop -----------------------------------------------------------

void setup() {
  pinMode(PIN_POWER_ON, OUTPUT);
  digitalWrite(PIN_POWER_ON, HIGH);

  btnNext.begin();
  btnAct.begin();
  analogReadResolution(12);

  // HWCDC defaults to a 256-byte RX queue, which is smaller than a single
  // weather response: the host streams the body faster than loop() drains it
  // and the tail is silently dropped, leaving every fetch to time out. Sized
  // above net_link's MAX_BODY so a whole reply always fits, buffered, even if
  // a render lands in the middle of it. Must precede begin(), which only
  // installs the default when no queue exists yet.
  Serial.setRxBufferSize(8192);
  Serial.setTxBufferSize(2048);   // a request URL alone overruns the 256 default
  Serial.begin(115200);
  delay(300);
  Serial.println("\n=== T-Display-S3 dashboard (landscape) ===");

  // Read before anything else can restart the panel, and kept for the system
  // page. The TWDT is already running with the IDF's five-second default and
  // nothing but the idle task subscribed; this widens it and puts the loop task
  // under it. panic = true so a trip leaves a backtrace on the way out —
  // monitor_filters has the decoder — rather than just a silent reboot.
  bootReason = esp_reset_reason();
  Serial.printf("[boot] last reset: %s\n", resetName(bootReason));

  esp_task_wdt_init(WDT_TIMEOUT_S, true);
  enableLoopWDT();
  Serial.printf("[wdt] watching the loop task, %lus\n",
                (unsigned long)WDT_TIMEOUT_S);

  tft.init();
  tft.setRotation(1);            // landscape, USB on the right
  tft.fillScreen(C_BG);
  pinMode(TFT_BL, OUTPUT);
  analogWrite(TFT_BL, backlight);

  fb.setColorDepth(16);
  if (!fb.createSprite(SCR_W, SCR_H)) {
    Serial.println("FATAL: could not allocate the frame buffer");
    tft.setTextColor(C_ERR, C_BG);
    tft.drawString("sprite alloc failed", 8, 60, 2);
    while (true) delay(1000);
  }

  // A font that fails to parse renders as nothing at all rather than failing
  // loudly, so confirm the metrics match what make_vlw.py wrote.
  for (auto &f : {std::pair<const char *, const uint8_t *>{"ui16", UiFont16},
                  std::pair<const char *, const uint8_t *>{"ui24", UiFont24},
                  std::pair<const char *, const uint8_t *>{"big64", BigFont64}}) {
    useFont(f.second);
    Serial.printf("[font] %-6s height=%2d width(\"20:45\")=%d\n",
                  f.first, fb.fontHeight(), fb.textWidth("20:45"));
  }
  useFont(nullptr);

  // Unconditionally, so the timezone applies to whatever the RTC already holds
  // — it survives a reset, and would otherwise be displayed as UTC. With no
  // network the SNTP client simply never syncs; over USB the bridge supplies
  // the epoch instead and this only decides how it is rendered.
  configTzTime(LOCAL_TZ, "pool.ntp.org", "time.google.com");

  net::setIdleHook(serviceWhileBlocked);
  net::begin();
}

void loop() {
  static uint32_t lastWeather = 0, lastUsage = 0, lastMac = 0,
                  lastCpu = 0, lastNotify = 0;
  static bool wasOnline = false;

  // Both are read every pass whatever happens to the result: pressed() debounces
  // against the level it saw last time, and a button that goes unpolled while a
  // banner is up would report the release as a press once it resumes.
  //
  // Either may also have been caught by the idle hook during a fetch. That
  // press is picked up here rather than lost with the pass it landed in.
  bool nextPressed = btnNext.pressed() || pendingNext;
  bool actPressed  = btnAct.pressed()  || pendingAct;
  pendingNext = pendingAct = false;

  // A banner is modal. The first press acknowledges it and does nothing else,
  // so clearing one never also flips the page or the backlight.
  if (notify.showing && (nextPressed || actPressed)) {
    notify.showing = false;
    nextPressed = actPressed = false;
    lastDraw = 0;
  }

  // Either button means a person is here, whatever it went on to do.
  if (nextPressed || actPressed) handOverToUser();

  if (nextPressed) {
    page = (page + 1) % PAGE_COUNT;
    lastDraw = 0;
    Serial.printf("[ui] page %u\n", page);
  }

  if (actPressed) {
    if (page == PAGE_NOW) {
      lastWeather = 0;                       // force a refresh
    } else if (page == PAGE_USAGE) {
      lastUsage = 0;
    } else if (page == PAGE_MAC) {
      lastMac = 0;
    } else {
      // Against the level actually showing, so a panel dimmed for the night
      // still comes up on the first press.
      blManual = backlight > BL_NIGHT ? BL_NIGHT : BL_DAY;
    }
    lastDraw = 0;
  }

  // net::loop() also drives the serial reader, so it has to run before the
  // command queue is drained — the two share the same stream of bytes.
  net::loop();

  for (int c = net::readCommand(); c >= 0; c = net::readCommand()) {
    switch (c) {
      // A page command from the host is a person driving too — grab_screen.py
      // walking the pages should not be raced by an automatic switch.
      case 'N': handOverToUser(); page = (page + 1) % PAGE_COUNT; render(); break;
      case 'S': dumpScreen(); break;
      case 'A':
        autoPages = !autoPages;
        autoReturn = -1;
        Serial.printf("[auto] page selection %s\n", autoPages ? "on" : "off");
        lastDraw = 0;
        break;
      default: break;
    }
  }

  bool online = net::online();
  if (online && !wasOnline) {
    Serial.printf("[net] link up over %s\n", net::viaName());
    lastWeather = 0;
    lastUsage = 0;
    lastMac = 0;
  }
  wasOnline = online;

  // NTP only reaches a server when WiFi is up. Over USB the host supplies the
  // epoch instead: once on arrival, then hourly, which is far more often than
  // the drift needs but costs one short round trip.
  static uint32_t lastTimeSync = 0, lastTimeTry = 0;
  bool timeValid = time(nullptr) > 1700000000;
  bool timeDue = !timeValid || lastTimeSync == 0 ||
                 millis() - lastTimeSync > 3600000UL;
  // Rate-limited separately from the success interval: a request that goes
  // unanswered blocks for its timeout, and retrying that every pass through
  // loop() would stall the clock rather than set it.
  if (net::via() == net::Via::Usb && timeDue &&
      (lastTimeTry == 0 || millis() - lastTimeTry > 10000UL)) {
    lastTimeTry = millis();
    if (net::syncTimeFromHost()) lastTimeSync = millis();
  }

  // Refresh on demand, then every 10 minutes. Retry sooner if it failed.
  uint32_t weatherAge = millis() - lastWeather;
  if (online && (lastWeather == 0 || weatherAge > (weather.valid ? 600000UL : 60000UL))) {
    lastWeather = millis();
    fetchWeather();
    lastDraw = 0;
  }

  // The cache moves every time Claude Code renders its status line, so poll
  // often — it is one small request to a machine on the same subnet.
  uint32_t usageAge = millis() - lastUsage;
  if (online && (lastUsage == 0 || usageAge > (usage.valid ? 30000UL : 15000UL))) {
    lastUsage = millis();
    fetchUsage();
    lastDraw = 0;
  }

  // Polled harder than the reading itself needs, because two of the panel's
  // automatic behaviours hang off it: the load average that picks the CPU page,
  // and the screen state that decides whether to stay lit. Ten seconds is about
  // how long a panel can stay dark after you unlock the Mac before it reads as
  // broken. The host answers out of a two-second cache in tens of milliseconds.
  if (online && (lastMac == 0 || millis() - lastMac > 10000UL)) {
    lastMac = millis();
    fetchMac();
    lastDraw = 0;
  }

  // The per-core page is the one thing here that wants a fresh reading every
  // second, and the only one polled solely while it is on screen: a blocking
  // request per second is worth it to watch cores move, and pure waste to keep
  // up behind a page nobody is looking at. Leaving lastCpu untouched off-page
  // means coming back to it fetches immediately.
  if (online && page == PAGE_CPU && millis() - lastCpu > 1000UL) {
    lastCpu = millis();
    fetchCpu();
    lastDraw = 0;
  }

  // Polled far harder than anything else, because this is the only reading
  // whose whole point is being noticed at once: a hook that stops to ask a
  // question is waiting on the answer. The request costs a couple of hundred
  // bytes and the host answers it out of a dict.
  if (online && millis() - lastNotify > 2000UL) {
    lastNotify = millis();
    if (fetchNotify()) lastDraw = 0;
  }

  // Messages with a ttl take themselves down. An alert has ttl 0 and waits for
  // a person, which is the point of being an alert — but not forever: nobody
  // may be coming, and a banner nobody dismisses is a panel stuck on one screen
  // that has also stopped choosing its own pages. Observed doing exactly that
  // for six minutes after the question it asked had already been answered.
  uint32_t life = notify.ttl ? notify.ttl : NOTIFY_ALERT_MAX;
  if (notify.showing && millis() - notify.raised > life * 1000UL) {
    notify.showing = false;
    lastDraw = 0;
  }

  updateBacklight();

  // Last, so it decides on this pass's readings rather than the previous one's.
  if (autoPickPage()) lastDraw = 0;

  if (millis() - lastDraw >= 1000) {
    lastDraw = millis();
    render();
  }

  delay(5);
}
