#!/usr/bin/env python3
"""Rasterise a TTF into TFT_eSPI's VLW smooth-font format, emitted as a C header.

TFT_eSPI ships a Processing sketch for this; this script replaces it so the whole
build stays in Python, and so we can pick the glyph set ourselves (Thai needs
codepoints the stock generator does not offer).

VLW layout, all fields big-endian int32:

    header   6 x int32   glyphCount, version, fontSize, unused, ascent, descent
    metrics  7 x int32   per glyph: codepoint, height, width, xAdvance, dY, dX, unused
    bitmaps              per glyph, width*height bytes of 8-bit alpha, glyph order

Picking a Thai font matters. TFT_eSPI does no OpenType shaping — it places each
codepoint at `cursor_x + dX` and advances by `xAdvance` — so Thai only comes out
right with a font whose combining marks already carry xAdvance == 0 and a
negative dX. macOS Sukhumvit Set does; macOS Thonburi does NOT (it bakes a
dotted-circle placeholder into every isolated mark glyph and gives it a real
advance, so vowels and tone marks land beside letters instead of above them).
Run preview_vlw.py after generating to check before flashing.

Usage:
    make_vlw.py <font.ttf> <pixel_size> <out.h> <c_symbol> [--face N] [--set S]

    --set ascii     printable ASCII + degree sign  (default)
    --set numeric    digits and number punctuation only, for big readouts
    --set thai       ASCII + the full Thai block

    # what this project uses
    make_vlw.py /System/Library/Fonts/Supplemental/SukhumvitSet.ttc \\
        16 src/fonts/ui16.h UiFont16 --face 2 --set ascii
"""

import sys
import struct
import freetype

# --- glyph set -------------------------------------------------------------

def charset(name):
    ascii_ = list(range(0x20, 0x7F)) + [0x00B0]   # printable ASCII + degree sign

    if name == "numeric":
        return [ord(c) for c in " 0123456789:.,-+/%°"]
    if name == "ascii":
        return ascii_
    if name == "thai":
        return (ascii_
                + list(range(0x0E01, 0x0E3B))     # Thai consonants + vowels
                + [0x0E3F]                        # baht sign
                + list(range(0x0E40, 0x0E4F))     # Thai vowels, tone marks
                + list(range(0x0E50, 0x0E5A)))    # Thai digits
    raise SystemExit(f"unknown --set {name!r} (ascii, numeric, thai)")


def main():
    opts = {"--face": "0", "--set": "ascii"}
    args, argv = [], sys.argv[1:]
    while argv:
        a = argv.pop(0)
        if a in opts:
            opts[a] = argv.pop(0)   # consume the flag's value, not just the flag
        else:
            args.append(a)

    if len(args) != 4:
        print(__doc__)
        return 1

    ttf, size, out_h, symbol = args[0], int(args[1]), args[2], args[3]
    face_index = int(opts["--face"])
    set_name = opts["--set"]

    face = freetype.Face(ttf, index=face_index)
    face.set_pixel_sizes(0, size)

    ascent = face.size.ascender >> 6
    descent = -(face.size.descender >> 6)

    metrics, bitmaps = [], []
    skipped = []

    for cp in charset(set_name):
        idx = face.get_char_index(cp)
        if idx == 0 and cp != 0x20:
            skipped.append(cp)
            continue

        face.load_char(cp, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
        g = face.glyph
        bm = g.bitmap

        w, h = bm.width, bm.rows
        adv = g.advance.x >> 6
        dx = g.bitmap_left
        dy = g.bitmap_top

        # TFT_eSPI truncates these on load, so anything out of range would render
        # as garbage rather than fail loudly. Clamp and report instead.
        if not (0 <= adv <= 255):
            print(f"  warn: U+{cp:04X} advance {adv} out of uint8 range, clamped")
            adv = max(0, min(255, adv))
        if not (-128 <= dx <= 127):
            print(f"  warn: U+{cp:04X} dX {dx} out of int8 range, clamped")
            dx = max(-128, min(127, dx))
        if w > 255 or h > 255:
            print(f"  warn: U+{cp:04X} bitmap {w}x{h} exceeds uint8, skipped")
            skipped.append(cp)
            continue

        # Rows are tightly packed in VLW; FreeType pads each row to its own pitch.
        rows = b"".join(
            bytes(bm.buffer[r * bm.pitch:(r * bm.pitch) + w]) for r in range(h))

        metrics.append((cp, h, w, adv, dy, dx))
        bitmaps.append(rows)

    blob = bytearray()
    blob += struct.pack(">6i", len(metrics), 11, size, 0, ascent, descent)
    for cp, h, w, adv, dy, dx in metrics:
        blob += struct.pack(">7i", cp, h, w, adv, dy, dx, 0)
    for b in bitmaps:
        blob += b

    # Raw .vlw alongside the header so preview_vlw.py can check what we emitted
    # rather than re-deriving it from the TTF.
    with open(out_h.rsplit(".", 1)[0] + ".vlw", "wb") as f:
        f.write(blob)

    with open(out_h, "w") as f:
        f.write(f"// Generated by tools/make_vlw.py from {ttf.split('/')[-1]} @ {size}px\n")
        f.write("// TFT_eSPI VLW smooth font. Do not edit by hand.\n")
        f.write("#pragma once\n#include <pgmspace.h>\n\n")
        f.write(f"const uint8_t {symbol}[] PROGMEM = {{\n")
        for i in range(0, len(blob), 16):
            f.write("  " + ",".join(f"0x{b:02X}" for b in blob[i:i + 16]) + ",\n")
        f.write("};\n")

    zero_adv = sum(1 for m in metrics if m[3] == 0)
    print(f"{out_h}: {len(metrics)} glyphs, {len(blob)/1024:.1f} KB, "
          f"ascent={ascent} descent={descent}, {zero_adv} zero-advance (combining)")
    if skipped:
        print(f"  missing from face: {' '.join(f'U+{c:04X}' for c in skipped)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
